# Generated by Django 6.0.7 on 2026-07-23 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Attendance', 'Attendance'), ('Leave', 'Leave'), ('Task', 'Task'), ('Project', 'Project')], max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=200)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
